### PR TITLE
feat: add support for GitLab

### PR DESCRIPTION
**Pull request by jasonwoods-7**
Adding support for syncing files in git repositories with GitLab

### CODE REVIEW

**Comment by jasonwoods-7** [comment]
Is this not wanted? I mean, I do get that the tool name is Git**Hub**Sync. If not, I'll just keep my fork around since I'm using it to keep ~60 repos in sync in GitLab using my modified version of the tool.

**Comment by SimonCropp** [comment]
i think it is a great idea. but i am worried about my ability to support it.

I would be happy for you to take a copy of the code and create a new project for gitlab. and will happily promote it

if there is a significant enough portion of code you want to re-use from this project, perhaps we can break that off into a "GitSync" nuget that both GitHubSync and GitLabSync could use

**Comment by SimonCropp** [comment]
and sorry for the delayed response

**Comment by jasonwoods-7** [comment]
That's a fair point.

I am reusing a lot of the code in the GitHubSync library. I'll look into separating the shared code out into a GitSync library.

**Comment by jasonwoods-7** [comment]
closing this pr in favor of #670

**Pull request closed without merging**
